name: ci

on:
    push:
        branches: [main]

jobs:
  style:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
            source: "."
            strict: "medium"
