
name: Lint and Commit
on:
    push:
      branches:
      - main
    pull_request:
      branches:
      - main
  

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install ruff
    - run: ruff check --fix .
    - uses: peter-evans/create-pull-request@v7
      with:
        commit-message: 'style fixes by ruff'
        branch: 'ruff/patch'